spring:
  application:
    name: sharp-test
#  datasource:
#    url: jdbc:postgresql://localhost:5432/test
#    username: postgres
#    password:
  datasource:
    url: ${JDBC.URL}
    username: ${JDBC.USERNAME}
    password: ${JDBC.PASSWORD}
  config:
    import:
      - optional:classpath:.env.postgres.properties

sharp:
  database:
    type: PostgreSQL
    entity-base-package: com.rick.test.**.entity, com.rick.test.**.select
    track-if-has-update: false

logging:
  level:
    root: WARN
#    org.springframework.jdbc.core: DEBUG
#    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    com:
      rick:
        test: DEBUG
        db:
          repository: DEBUG


springdoc:
  kotlin:
    enabled: true
  api-docs:
    path: /api-docs

